version: '3.9'


services:
  postgres17:
   image: postgres:17.0
   container_name: postgres17
   volumes:
     - /c/docker_workspace/postgres17:/var/lib/postgresql/data
   command: 'postgres'
   ports:
     - '${PORT}:5432'
   stdin_open: true
   tty: true
   env_file:
     - .env
   environment:
    - POSTGRES_DB=$DB
    - POSTGRES_USER=$USER
    - POSTGRES_PASSWORD=$PASSWORD
